networks:
  app-tier:
    driver: bridge

services:
  demo-app:
    build:
      context: ../
      dockerfile: Dockerfile
    hostname: demo-app
    container_name: demo-app
    ports:
      - "8080:8080"
    networks:
      - app-tier

  redis-master:
    image: "bitnami/redis:7.2.4"
    hostname: redis-master
    container_name: redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    ports:
      - "5100:6379"
    networks:
      - app-tier

  redis-slave-1:
    image: "bitnami/redis:7.2.4"
    hostname: redis-slave-1
    container_name: redis-slave-1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_REPLICATION_MODE=slave
    ports:
      - "5101:6379"
    depends_on:
      - redis-master
    networks:
      - app-tier

  redis-slave-2:
    image: "bitnami/redis:7.2.4"
    hostname: redis-slave-2
    container_name: redis-slave-2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_REPLICATION_MODE=slave
    ports:
      - "5102:6379"
    depends_on:
      - redis-master
      - redis-slave-1
    networks:
      - app-tier

  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:7.2.4'
    hostname: redis-sentinel-1
    container_name: redis-sentinel-1
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000 # sentinel 이 마스터노드 장애여부 판단하는 시간
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2 # 마스터 다운에 대한 동의를 해야하는 sentinel 수
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - '5150:26379'
    networks:
      - app-tier

  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:7.2.4'
    hostname: redis-sentinel-2
    container_name: redis-sentinel-2
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - '5151:26379'
    networks:
      - app-tier

  redis-sentinel-3:
    image: 'bitnami/redis-sentinel:7.2.4'
    hostname: redis-sentinel-3
    container_name: redis-sentinel-3
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - '5152:26379'
    networks:
      - app-tier